name: bump

on: 
  repository_dispatch:

jobs:
  bump:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Information
      run: |
        echo "Version update for ${{ github.event.client_payload.package_version }}, job id ${{ github.event.client_payload.run_id }} requested"

    - uses: actions/checkout@v4

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        run_id: ${{ github.event.client_payload.run_id }}
        repo: PhotonVision/photonvision

    - run: find .
