name: bump

on: 
  repository_dispatch:

jobs:
  bump:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Information
      run: |
        echo "Version update for ${{ github.event.client_payload.package_version }}, job id ${{ github.event.client_payload.run_id }} requested"

    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: photonlib-vendor-json
        github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
        repository: mcm001/photonvision
        run-id: ${{ github.event.client_payload.run_id }}
        merge-multiple: true
        path: "2025"

    - run: find .
    - run: git status
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: python3 fixup_year.py 2025
